### ISSUE TITLE
Default Credentials for Docker Compose

### ISSUE THREAD

**Issue by Herobr1ne** [dicedtomatoreal/typex#100]
Hey,
I installed Zipline with Docker-Compose but what are the default Login Credentials for the Panel? Or how can i create a new user?
I tryed "administrator" "password" but this error appears in the log

zipline_1   | 2021-09-09 05:04:16,076 PM INFO  [url] 200: /api/auth/login
zipline_1   | PrismaClientKnownRequestError3 [PrismaClientKnownRequestError]:
zipline_1   | Invalid `prisma.user.findMany()` invocation:
zipline_1   |
zipline_1   |
zipline_1   |   The table `public.User` does not exist in the current database.
zipline_1   |     at cb (/zipline/node_modules/@prisma/client/runtime/index.js:36494:17)
zipline_1   |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
zipline_1   |     at async handler (/zipline/.next/server/pages/api/auth/login.js:31:17)
zipline_1   |     at async Object.apiResolver (/zipline/node_modules/next/dist/server/api-utils.js:101:9)
zipline_1   |     at async Server.handleApiRequest (/zipline/node_modules/next/dist/server/next-server.js:770:9)
zipline_1   |     at async Object.fn (/zipline/node_modules/next/dist/server/next-server.js:661:37)
zipline_1   |     at async Router.execute (/zipline/node_modules/next/dist/server/router.js:205:32)
zipline_1   |     at async Server.run (/zipline/node_modules/next/dist/server/next-server.js:841:29)
zipline_1   |     at async Server.handleRequest (/zipline/node_modules/next/dist/server/next-server.js:292:20) {
zipline_1   |   code: 'P2021',
zipline_1   |   clientVersion: '2.30.3',
zipline_1   |   meta: { table: 'public.User' }
zipline_1   | }

Best wishes
Herobr1ne

**Comment by Herobr1ne** [comment]
Execute "yarn prisma migrate deploy"
Now it works
