### ISSUE TITLE
Error When Running in Docker

### ISSUE THREAD

**Issue by cojored** [dicedtomatoreal/typex#108]
2021-10-26 09:20:47,190 PM INFO  [server] starting zipline@3.2.5 server
2021-10-26 09:20:47,193 PM INFO  [config] reading config file
2021-10-26 09:20:47,194 PM ERROR [server] Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (node:fs:723:3)
    at tryReadSync (node:fs:433:20)
    at readFileSync (node:fs:479:19)
    at module.exports (/zipline/src/lib/readConfig.js:31:17)
    at /zipline/server/index.js:37:15
    at Object.<anonymous> (/zipline/server/index.js:138:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)

**Comment by diced** [comment]
What OS are you running on?

**Comment by cojored** [comment]
Ubuntu 21.04

**Comment by diced** [comment]
Not sure why this is happening, make sure the directory has full permissions.

**Comment by diced** [comment]
Closing due to inactivity
