### ISSUE TITLE
Requirement

### ISSUE THREAD

**Issue by hexlocation** [dicedtomatoreal/typex#114]
Maybe put postgreSQL / Postgres as requirement @ the documentation, and what is the default username & password?

I get spammed with this error when using docker-compose:
zipline_1   | 2021-12-27 06:29:55,872 PM INFO  [server] starting zipline@3.2.5 server
zipline_1   | 2021-12-27 06:29:55,874 PM INFO  [config] reading environment
zipline_1   | 2021-12-27 06:29:55,879 PM ERROR [server] 1 errors occured
zipline_1   |   urls.route is a required field
zipline_zipline_1 exited with code 1

**Comment by hexlocation** [comment]
Please make sure your database server is running at `postgres`:`5432`.
    at cb (/root/zipline/node_modules/@prisma/client/runtime/index.js:38694:17)
    at async handler (/root/zipline/.next/server/pages/api/auth/login.js:31:17)
    at async Object.apiResolver (/root/zipline/node_modules/next/dist/server/api-utils.js:101:9)
    at async Server.handleApiRequest (/root/zipline/node_modules/next/dist/server/next-server.js:770:9)
    at async Object.fn (/root/zipline/node_modules/next/dist/server/next-server.js:661:37)
    at async Router.execute (/root/zipline/node_modules/next/dist/server/router.js:205:32)
    at async Server.run (/root/zipline/node_modules/next/dist/server/next-server.js:841:29)
    at async Server.handleRequest (/root/zipline/node_modules/next/dist/server/next-server.js:292:20) {
  clientVersion: '3.7.0',
  errorCode: undefined
}
with manual installation with node
also it cant connect to the postgresql database?

**Comment by mzch** [comment]
`docker-compose.yml` in `trunk` branch is incomplete. You have to add `URLS_ROUTE` and `URLS_LENGTH` environment variables. See https://zipline.diced.cf/docs/config/sections/urls
