### ISSUE TITLE
ShareX Issue

### ISSUE THREAD

**Issue by ar065** [dicedtomatoreal/typex#170]
There is an issue with shortening URLs. It simply doesn't work:
```
Status code:
(500) Internal Server Error

Response URL:
https://[REDACTED].com/api/upload

Headers:
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Content-Allow-Methods: GET,HEAD,POST,OPTIONS
Access-Control-Max-Age: 86400
Vary: Accept-Encoding
Content-Type: application/json
Date: Fri, 09 Sep 2022 21:45:28 GMT
Server: openresty

Response text:
{"error":"no files"}
```
The URL sharing is pretty much the same, but there are some slight differences:
```
URL:
https://getsharex.com

Error:
Error message:
The remote server returned an error: (500) Internal Server Error.

Request URL:
https://[REDACTED].com/api/upload

Status code:
(500) Internal Server Error

Headers:
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Content-Allow-Methods: GET,HEAD,POST,OPTIONS
Access-Control-Max-Age: 86400
Vary: Accept-Encoding
Content-Type: application/json
Date: Fri, 09 Sep 2022 21:46:35 GMT
Server: openresty

Response text:
{"error":"no files"}

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Stream data, String contentType, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, Boolean allowNon2xxResponses)
   ```
This was all done via clicking the "Test" buttons on ShareX

**Comment by diced** [comment]
You are accessing the wrong endpoint for shortening urls, it should be /api/shorten

**Comment by ar06x** [comment]
> You are accessing the wrong endpoint for shortening urls, it should be /api/shorten

Wouldn't that be included in the ShareX config? Interesting if not. Thank you for sharing the information on why this issue is occurring for me

**Comment by diced** [comment]
> Wouldn't that be included in the ShareX config?

It isn't, the ShareX config buttons on the user page are only for uploading files. The next release may have a better version to generate sharex configurations, so stay tuned!
