### ISSUE TITLE
Bug: Cannot preview images through dashboard

### ISSUE THREAD

**Issue by Retr0-01** [dicedtomatoreal/typex#208]
### What happened?

Clicking on an image in the recent files section of the dashboard gives out the following errors in the client console:
![chrome_SlECEFWwM4](https://user-images.githubusercontent.com/61121754/199295966-5eae4273-4b70-4377-a364-4d1b657849d7.png)

No further errors (such as from server-side logs) have been thrown.

### Version

latest

### What browser(s) are you seeing the problem on?

Chrome

### Browser Logs

```shell
TypeError: Cannot destructure property 'auth' of 'e' as it is undefined.
    at o (main-d2a793b6dc23a82a.js:1:61952)
    at t.formatWithValidation (main-d2a793b6dc23a82a.js:1:61840)
    at Object.U [as resolveHref] (main-d2a793b6dc23a82a.js:1:41572)
    at 178-22237ed463710e4a.js:1:3285
    at Object.useMemo (framework-3b5a00d5d7e8d93b.js:1:67319)
    at n.useMemo (framework-3b5a00d5d7e8d93b.js:1:135806)
    at 178-22237ed463710e4a.js:1:3261
    at ak (framework-3b5a00d5d7e8d93b.js:1:61009)
    at ui (framework-3b5a00d5d7e8d93b.js:1:71320)
    at i (framework-3b5a00d5d7e8d93b.js:1:121651)
TypeError: Cannot destructure property 'auth' of 'e' as it is undefined.
    at o (main-d2a793b6dc23a82a.js:1:61952)
    at t.formatWithValidation (main-d2a793b6dc23a82a.js:1:61840)
    at Object.U [as resolveHref] (main-d2a793b6dc23a82a.js:1:41572)
    at 178-22237ed463710e4a.js:1:3285
    at Object.useMemo (framework-3b5a00d5d7e8d93b.js:1:67319)
    at n.useMemo (framework-3b5a00d5d7e8d93b.js:1:135806)
    at 178-22237ed463710e4a.js:1:3261
    at ak (framework-3b5a00d5d7e8d93b.js:1:61009)
    at ui (framework-3b5a00d5d7e8d93b.js:1:71320)
    at i (framework-3b5a00d5d7e8d93b.js:1:121651)
```

**Comment by diced** [comment]
Fixed in https://github.com/diced/zipline/commit/564fcfca611ead9aea989a8b7d9f99cfc12240eb
