### ISSUE TITLE
Bug: `User.oauth` does not exist in the current database.

### ISSUE THREAD

**Issue by freegamerskids** [dicedtomatoreal/typex#220]
### What happened?

Title, console logs in the logs section.

### Version

upstream

### What browser(s) are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Zipline Logs

```shell
The column `User.oauth` does not exist in the current database.
    at RequestHandler.handleRequestError (/zipline/node_modules/@prisma/client/runtime/index.js:30873:13)
    at RequestHandler.request (/zipline/node_modules/@prisma/client/runtime/index.js:30856:12)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async PrismaClient._request (/zipline/node_modules/@prisma/client/runtime/index.js:31836:16)
    at start (/zipline/src/server/index.ts:43:17) {
  code: 'P2022',
  clientVersion: '4.5.0',
  meta: { column: 'User.oauth' }
}
```

**Comment by freegamerskids** [comment]
Fixed it. Closing issue.

Whoever gets this issue, just update zipline.
