### ISSUE TITLE
Bug: U h... Zipline decided to die on update

### ISSUE THREAD

**Issue by DIVISIONSolar** [dicedtomatoreal/typex#243]
### What happened?

Not sure what happened but after I updated zipline I've been getting bad gateway errors

### Version

latest (ghcr.io/diced/zipline:latest)

### Zipline Logs

```shell
zipline-zipline-1 exited with code 1
zipline-zipline-1   | 2022-12-10 12:25:36,704 AM info  [datasource] using Local(./uploads) datasource
zipline-postgres-1  | 2022-12-10 00:25:37.630 UTC [46] LOG:  could not receive data from client: Connection reset by peer
zipline-zipline-1   | 2022-12-10 12:25:39,042 AM info  [server] started production zipline@3.6.3 server
zipline-zipline-1   | 2022-12-10 12:25:39,045 AM info  [server] listening on 0.0.0.0:3000
zipline-zipline-1   | /zipline/node_modules/@prisma/client/runtime/index.js:32393
zipline-zipline-1   |     const error2 = new PrismaClientValidationError(renderErrorStr(validationCallsite));
zipline-zipline-1   |                    ^
zipline-zipline-1   | 
zipline-zipline-1   | PrismaClientValidationError: Argument id for where.id must not be null. Please use undefined instead.
zipline-zipline-1   | 
zipline-zipline-1   |     at Document.validate (/zipline/node_modules/@prisma/client/runtime/index.js:32393:20)
zipline-zipline-1   |     at serializationFn (/zipline/node_modules/@prisma/client/runtime/index.js:35967:19)
zipline-zipline-1   |     at runInChildSpan (/zipline/node_modules/@prisma/client/runtime/index.js:25431:12)
zipline-zipline-1   |     at PrismaClient._executeRequest (/zipline/node_modules/@prisma/client/runtime/index.js:35974:31)
zipline-zipline-1   |     at applyQueryExtensions (/zipline/node_modules/@prisma/client/runtime/index.js:34305:19)
zipline-zipline-1   |     at consumer (/zipline/node_modules/@prisma/client/runtime/index.js:35898:18)
zipline-zipline-1   |     at /zipline/node_modules/@prisma/client/runtime/index.js:35903:51
zipline-zipline-1   |     at AsyncResource.runInAsyncScope (node:async_hooks:204:9)
zipline-zipline-1   |     at /zipline/node_modules/@prisma/client/runtime/index.js:35903:29
zipline-zipline-1   |     at runInChildSpan (/zipline/node_modules/@prisma/client/runtime/index.js:25431:12) {
zipline-zipline-1   |   clientVersion: '4.7.0'
zipline-zipline-1   | }
zipline-zipline-1   | 
zipline-zipline-1   | Node.js v19.2.0
zipline-zipline-1 exited with code 1
zipline-zipline-1   | 2022-12-10 12:25:41,244 AM info  [datasource] using Local(./uploads) datasource
```

**Comment by diced** [comment]
Fixed
