### ISSUE TITLE
Bug: Error P3009 failed to migrate database on fresh clone

### ISSUE THREAD

**Issue by dilllxd** [dicedtomatoreal/typex#261]
### What happened?

The steps to reproduce the bug:
1. Cloned the repo
2. Changed directory to the clone and changed the core_secret
3. Executed "docker compose up -d"
4. Checked the logs file in Portainer, now getting Error: P3009.

Your OS & Browser including server OS: Win 11 Pro 22H2 22621.963 - Brave Browser - Debian 5.10.158-2

This was just a fresh install, just found the project and wanted to install it and test it. Let me know if there is anything I can do/provide to help.

### Version

upstream (ghcr.io/diced/zipline:trunk)

### What browser(s) are you seeing the problem on?

Chromium-based (Chrome, Edge, Brave, Opera, mobile chrome/chromium based, etc)

### Zipline Logs

```shell
2023-01-05 07:06:52,025 PM info  [datasource] using Local(./uploads) datasource
2023-01-05 07:06:52,884 PM info  [database::migrations] finished migrating database
2023-01-05 07:06:52,884 PM error [database::migrations] Failed to migrate database... exiting...
2023-01-05 07:06:52,885 PM error [database::migrations] Error: P3009
migrate found failed migrations in the target database, new migrations will not be applied. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve
The `20210924050753_new_url` migration started at 2023-01-05 18:20:54.983641 UTC failed
    at Object.<anonymous> (/zipline/node_modules/@prisma/migrate/dist/MigrateEngine.js:279:24)
    at MigrateEngine.handleResponse (/zipline/node_modules/@prisma/migrate/dist/MigrateEngine.js:132:36)
    at LineStream.<anonymous> (/zipline/node_modules/@prisma/migrate/dist/MigrateEngine.js:231:16)
    at LineStream.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at LineStream._pushBuffer (/zipline/node_modules/@prisma/migrate/dist/utils/byline.js:104:17)
    at LineStream._transform (/zipline/node_modules/@prisma/migrate/dist/utils/byline.js:98:8)
    at Transform._write (node:internal/streams/transform:175:8)
```

### Browser Logs

```shell
Haven't been able to even get to the website yet.
```

### Additional Info

Here's my config, I'll change the core_secret when I get it working properly :)

version: '3'
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  zipline:
    image: ghcr.io/diced/zipline
    ports:
      - '3000:3000'
    restart: always
    environment:
      - CORE_RETURN_HTTPS=false
      - CORE_SECRET=kDfxQt6HvE6TfjLzAMcj9bjxjRmn9o
      - CORE_HOST=0.0.0.0
      - CORE_PORT=3000
      - CORE_DATABASE_URL=postgres://postgres:postgres@postgres/postgres
      - CORE_LOGGER=true
    volumes:
      - './uploads:/zipline/uploads'
      - '$PWD/public:/zipline/public'
    depends_on:
      - 'postgres'

volumes:
  pg_data:

**Comment by TacticalTechJay** [comment]
Do you have any logs from postgres for when it treid to apply the migrations?

**Comment by dilllxd** [comment]
[_zipline-postgres-1_logs.txt](https://github.com/diced/zipline/files/10355178/_zipline-postgres-1_logs.txt)
This should be the log file.

didn't mean to close, sorry. kinda new to github issues lol

**Comment by dilllxd** [comment]
I literally restarted the computer, deleted all the containers and retried it and it works now. Welp! Thanks for attempting to help.
