### ISSUE TITLE
Bug: Profile Page "Something went wrong..."

### ISSUE THREAD

**Issue by TwoBrake** [dicedtomatoreal/typex#272]
### What happened?

When I try clicking on the profile page in the top right where it displays your username and avatar, it brings me to an error page saying that "Something went wrong...".
![5JduBK](https://user-images.githubusercontent.com/78281961/213591050-3aae2fe6-703c-44fd-bbaa-201aad69ecf1.png)
I don't know what is wrong, this used to be working but suddenly just started producing this error.

### Version

latest (ghcr.io/diced/zipline:latest)

### What browser(s) are you seeing the problem on?

Firefox, Chromium-based (Chrome, Edge, Brave, Opera, mobile chrome/chromium based, etc), Safari, Firefox Mobile, Safari Mobile

### Browser Logs

```shell
framework-1aa899be9db520d4.js:9 Error: Menu component was not found in the tree
    at r (85516-3dcecd829fb618b5.js:1:21344)
    at 54915-a3ca6a0762003aa1.js:1:38032
    at ak (framework-1aa899be9db520d4.js:9:60918)
    at ui (framework-1aa899be9db520d4.js:9:71229)
    at i (framework-1aa899be9db520d4.js:9:121561)
    at oD (framework-1aa899be9db520d4.js:9:99115)
    at framework-1aa899be9db520d4.js:9:98982
    at oO (framework-1aa899be9db520d4.js:9:98989)
    at oE (framework-1aa899be9db520d4.js:9:95741)
    at ox (framework-1aa899be9db520d4.js:9:94296)
a9 @ framework-1aa899be9db520d4.js:9
main-e5277298906f66b4.js:1 Error: Menu component was not found in the tree
    at r (85516-3dcecd829fb618b5.js:1:21344)
    at 54915-a3ca6a0762003aa1.js:1:38032
    at ak (framework-1aa899be9db520d4.js:9:60918)
    at ui (framework-1aa899be9db520d4.js:9:71229)
    at i (framework-1aa899be9db520d4.js:9:121561)
    at oD (framework-1aa899be9db520d4.js:9:99115)
    at framework-1aa899be9db520d4.js:9:98982
    at oO (framework-1aa899be9db520d4.js:9:98989)
    at oE (framework-1aa899be9db520d4.js:9:95741)
    at ox (framework-1aa899be9db520d4.js:9:94296)
$ @ main-e5277298906f66b4.js:1
main-e5277298906f66b4.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
$ @ main-e5277298906f66b4.js:1
framework-1aa899be9db520d4.js:9 Error: Menu component was not found in the tree
    at r (85516-3dcecd829fb618b5.js:1:21344)
    at 54915-a3ca6a0762003aa1.js:1:32439
    at ak (framework-1aa899be9db520d4.js:9:60918)
    at ui (framework-1aa899be9db520d4.js:9:71229)
    at i (framework-1aa899be9db520d4.js:9:121561)
    at oD (framework-1aa899be9db520d4.js:9:99115)
    at framework-1aa899be9db520d4.js:9:98982
    at oO (framework-1aa899be9db520d4.js:9:98989)
    at oE (framework-1aa899be9db520d4.js:9:95741)
    at ox (framework-1aa899be9db520d4.js:9:94296)
a9 @ framework-1aa899be9db520d4.js:9
main-e5277298906f66b4.js:1 Error: Menu component was not found in the tree
    at r (85516-3dcecd829fb618b5.js:1:21344)
    at 54915-a3ca6a0762003aa1.js:1:32439
    at ak (framework-1aa899be9db520d4.js:9:60918)
    at ui (framework-1aa899be9db520d4.js:9:71229)
    at i (framework-1aa899be9db520d4.js:9:121561)
    at oD (framework-1aa899be9db520d4.js:9:99115)
    at framework-1aa899be9db520d4.js:9:98982
    at oO (framework-1aa899be9db520d4.js:9:98989)
    at oE (framework-1aa899be9db520d4.js:9:95741)
    at ox (framework-1aa899be9db520d4.js:9:94296)
$ @ main-e5277298906f66b4.js:1
main-e5277298906f66b4.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
$ @ main-e5277298906f66b4.js:1
main-e5277298906f66b4.js:1 Error rendering page:  Error: Cancel rendering route
    at c (main-e5277298906f66b4.js:1:12315)
    at main-e5277298906f66b4.js:1:12267
    at new Promise (<anonymous>)
    at ea (main-e5277298906f66b4.js:1:12244)
    at main-e5277298906f66b4.js:1:10856
```

**Comment by IceToast** [comment]
The Mantine Menu component is missing as parent of the Menu sub components.
