### ISSUE TITLE
Bug: TypeError: server.next is not a function

### ISSUE THREAD

**Issue by RaithSphere** [dicedtomatoreal/typex#319]
### What happened?

Just did a fresh install using docker

Applying migration `20210825043706_init`
Applying migration `20210826034827_custom_themes`
Applying migration `20210827202147_favorite`
Applying migration `20210830210159_zws`
Applying migration `20210901024501_embed_image`
Applying migration `20210924045900_delete_url`
Applying migration `20210924050753_new_url`
/zipline/src/server/index.ts:166
    server.next('/*', { method: 'ALL' });
           ^

TypeError: server.next is not a function
    at <anonymous> (/zipline/src/server/index.ts:166:12)
    at Object._encapsulateThreeParam (/zipline/node_modules/avvio/boot.js:539:13)
    at Boot.timeoutCall (/zipline/node_modules/avvio/boot.js:453:5)
    at Boot.callWithCbOrNextTick (/zipline/node_modules/avvio/boot.js:435:19)
    at Boot._after (/zipline/node_modules/avvio/boot.js:280:26)
    at Plugin.exec (/zipline/node_modules/avvio/plugin.js:130:19)
    at Boot.loadPlugin (/zipline/node_modules/avvio/plugin.js:272:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

### Version

latest (ghcr.io/diced/zipline:latest)

**Comment by RaithSphere** [comment]
Just to point out not having this issue on the Trunk version

**Comment by TacticalTechJay** [comment]
I can't seem to be able to reproduce this on a fresh docker container

**Comment by TacticalTechJay** [comment]
Do you use the `docker-compose.yml` file?

**Comment by diced** [comment]
Also not able to reproduce, I will be closing this as stale. My recommendation is to just restart Zipline if you encounter this again.
