### ISSUE TITLE
Bug: Can't use query size script to fix file sizes when using S3 (B2)

### ISSUE THREAD

**Issue by NebulaBC** [dicedtomatoreal/typex#350]
### What happened?

When running `docker compose exec zipline yarn scripts:query-size` I get:
```js
/zipline/node_modules/minio/dist/main/transformers.js:149
      var e = new errors.S3Error(message); // S3 Error code.
              ^
S3Error: Not Found
    at getError (/zipline/node_modules/minio/dist/main/transformers.js:149:15)
    at /zipline/node_modules/minio/dist/main/transformers.js:161:14
    at DestroyableTransform._flush (/zipline/node_modules/minio/dist/main/transformers.js:91:10)
    at DestroyableTransform.prefinish (/zipline/node_modules/readable-stream/lib/_stream_transform.js:129:10)
    at DestroyableTransform.emit (node:events:513:28)
    at prefinish (/zipline/node_modules/readable-stream/lib/_stream_writable.js:611:14)
    at finishMaybe (/zipline/node_modules/readable-stream/lib/_stream_writable.js:620:5)
    at endWritable (/zipline/node_modules/readable-stream/lib/_stream_writable.js:643:3)
    at Writable.end (/zipline/node_modules/readable-stream/lib/_stream_writable.js:571:22)
    at IncomingMessage.onend (node:internal/streams/readable:705:10) {
  code: 'NotFound',
  amzRequestid: null,
  amzId2: null,
  amzBucketRegion: null
}

Node.js v18.15.0
error Command failed with exit code 1.
```

### Version

upstream (ghcr.io/diced/zipline:trunk)

### Additional Info

I'm using Backblaze's implementation of S3.

**Comment by diced** [comment]
#363 Does this PR (latest commit as of now), fix any of the issues here?

**Comment by TacticalTechJay** [comment]
Hey there @NebulaBC, just checking in to see if your issue was resolved. Has there been any issue since #363?

**Comment by NebulaBC** [comment]
Nope, after pulling and restarting my container I’m still getting the same error when I try to run this script.

**Comment by diced** [comment]
Reopened, until we see a response from @NebulaBC - hope the fix works!

**Comment by TacticalTechJay** [comment]
@NebulaBC, has the following commit (3ff2153) fixed your issue?

**Comment by NebulaBC** [comment]
This problem is solved, thanks. Sorry for the delay, Github is not my primary git platform.
