### ISSUE TITLE
Bug: Node errors out and crashes on first install

### ISSUE THREAD

**Issue by smishcraft** [dicedtomatoreal/typex#354]
### What happened?

I am using the docker images, 

I installed it following the instructions and also put ssl on the reverse proxy, resulting in the 3 dots appearing top left and the below error in the logs.

This also happens if I try to go direct to port 3000 using the machines IP.

### Version

latest (ghcr.io/diced/zipline:latest)

### What browser(s) are you seeing the problem on?

Chromium-based (Chrome, Edge, Brave, Opera, mobile chrome/chromium based, etc)

### Zipline Logs

```shell
2023-03-31 03:41:22,990 PM info  [datasource] using Local(./uploads) datasource
2023-03-31 03:41:23,041 PM info  [database::migrations] establishing database connection
2023-03-31 03:41:23,042 PM info  [database::migrations] ensuring database exists, if not creating database - may error if no permissions
2023-03-31 03:41:23,478 PM info  [database::migrations] finished migrating database
2023-03-31 03:41:25,836 PM info  [server] listening on 0.0.0.0:3000
2023-03-31 03:41:25,836 PM info  [server] started production zipline@3.7.0 server
2023-03-31 03:41:27,493 PM info  [server::response] GET /dashboard -> 200
/zipline/src/server/decorators/postFile.ts:21
      this.server.logger

           ^
TypeError: Cannot read properties of null (reading 'id')
    at _Reply.postUrl (/zipline/src/server/decorators/postFile.ts:21:12)
    at Object.urlsRouteOnResponse (/zipline/src/server/routes/uploads.ts:17:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Node.js v18.15.0
2023-03-31 03:41:30,682 PM info  [datasource] using Local(./uploads) datasource
2023-03-31 03:41:30,733 PM info  [database::migrations] establishing database connection
2023-03-31 03:41:30,734 PM info  [database::migrations] ensuring database exists, if not creating database - may error if no permissions
2023-03-31 03:41:30,895 PM info  [database::migrations] exiting migrations engine - database is up to date
2023-03-31 03:41:33,130 PM info  [server] listening on 0.0.0.0:3000
2023-03-31 03:41:33,130 PM info  [server] started production zipline@3.7.0 server
2023-03-31 03:43:18,565 PM info  [server::response] GET /r/chrome_2023-03-31_15-20-41.png -> 404
2023-03-31 03:43:27,996 PM info  [server::response] GET /dashboard -> 200
/zipline/src/server/decorators/postFile.ts:21
      this.server.logger

           ^
TypeError: Cannot read properties of null (reading 'id')
    at _Reply.postUrl (/zipline/src/server/decorators/postFile.ts:21:12)
    at Object.urlsRouteOnResponse (/zipline/src/server/routes/uploads.ts:17:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Node.js v18.15.0
2023-03-31 03:43:31,270 PM info  [datasource] using Local(./uploads) datasource
2023-03-31 03:43:31,322 PM info  [database::migrations] establishing database connection
2023-03-31 03:43:31,323 PM info  [database::migrations] ensuring database exists, if not creating database - may error if no permissions
2023-03-31 03:43:31,487 PM info  [database::migrations] exiting migrations engine - database is up to date
2023-03-31 03:43:33,708 PM info  [server] listening on 0.0.0.0:3000
2023-03-31 03:43:33,708 PM info  [server] started production zipline@3.7.0 server
2023-03-31 03:45:00,388 PM info  [server::response] GET /r/chrome_2023-03-31_15-20-41.png -> 404
2023-03-31 03:45:10,336 PM info  [server::response] GET / -> 302
2023-03-31 03:45:11,536 PM info  [server::response] GET /dashboard -> 200
/zipline/src/server/decorators/postFile.ts:21
      this.server.logger

           ^
TypeError: Cannot read properties of null (reading 'id')
    at _Reply.postUrl (/zipline/src/server/decorators/postFile.ts:21:12)
    at Object.urlsRouteOnResponse (/zipline/src/server/routes/uploads.ts:17:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Node.js v18.15.0
2023-03-31 03:45:14,886 PM info  [datasource] using Local(./uploads) datasource
2023-03-31 03:45:14,938 PM info  [database::migrations] establishing database connection
2023-03-31 03:45:14,940 PM info  [database::migrations] ensuring database exists, if not creating database - may error if no permissions
2023-03-31 03:45:15,105 PM info  [database::migrations] exiting migrations engine - database is up to date
2023-03-31 03:45:17,402 PM info  [server] listening on 0.0.0.0:3000
2023-03-31 03:45:17,402 PM info  [server] started production zipline@3.7.0 server
2023-03-31 03:47:11,442 PM info  [server::response] GET /dashboard -> 200
/zipline/src/server/decorators/postFile.ts:21
      this.server.logger

           ^
TypeError: Cannot read properties of null (reading 'id')
    at _Reply.postUrl (/zipline/src/server/decorators/postFile.ts:21:12)
    at Object.urlsRouteOnResponse (/zipline/src/server/routes/uploads.ts:17:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Node.js v18.15.0
2023-03-31 03:47:14,721 PM info  [datasource] using Local(./uploads) datasource
2023-03-31 03:47:14,772 PM info  [database::migrations] establishing database connection
2023-03-31 03:47:14,774 PM info  [database::migrations] ensuring database exists, if not creating database - may error if no permissions
2023-03-31 03:47:14,941 PM info  [database::migrations] exiting migrations engine - database is up to date
2023-03-31 03:47:17,332 PM info  [server] listening on 0.0.0.0:3000
2023-03-31 03:47:17,333 PM info  [server] started production zipline@3.7.0 server
```

### Additional Info

version: '3'
services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  zipline:
    image: ghcr.io/diced/zipline
    ports:
      - '3000:3000'
    restart: unless-stopped
    environment:
      - CORE_RETURN_HTTPS=false
      - CORE_SECRET=penisshit
      - CORE_HOST=0.0.0.0
      - CORE_PORT=3000
      - CORE_DATABASE_URL=postgres://postgres:postgres@postgres/postgres
      - CORE_LOGGER=true
      - URLS_ROUTE=/
    volumes:
      - './uploads:/zipline/uploads'
      - '$PWD/public:/zipline/public'
    depends_on:
      - 'postgres'

volumes:
  pg_data:

**Comment by smishcraft** [comment]
Through testing, I have found it does not like `- URLS_ROUTE=/`  If you put another / in it generates urls with 3 / when the desired result is domain.co/jhjdfu

**Comment by TacticalTechJay** [comment]
I'm not quite following. Are you saying that if `URLS_ROUTE` is set to `//`, it'll generate urls with `///`?

**Comment by smishcraft** [comment]
Yes, a single "/" crashes node when you try to access the dashboard and "//" creates urls with `///` for example domain.co///djhfs

**Comment by TacticalTechJay** [comment]
The `///` result seems to be working as intended. The route that was set in config is expected to not end in a `/` so that it can be added later on upload or url shorten.
