### ISSUE TITLE
Bug: Failed to migrate database. Error: P3009

### ISSUE THREAD

**Issue by danshaw** [dicedtomatoreal/typex#374]
### What happened?

Trying to figure out why I am getting the "Failed to migrate database" error when trying to set this up for the first time. I'm using the latest build and my Docker is running on a Synology NAS which shouldn't be a problem. 

It's similar to this issue - https://github.com/diced/zipline/issues/261

### Version

latest (ghcr.io/diced/zipline:latest)

### What browser(s) are you seeing the problem on?

Firefox, Chromium-based (Chrome, Edge, Brave, Opera, mobile chrome/chromium based, etc), Safari, Firefox Mobile, Safari Mobile

### Zipline Logs

```shell
2023-04-16 07:16:54,899 PM info  [datasource] using Local(./uploads) datasource
2023-04-16 07:16:54,928 PM info  [database::migrations] establishing database connection
2023-04-16 07:16:54,928 PM info  [database::migrations] ensuring database exists, if not creating database - may error if no permissions
2023-04-16 07:16:55,044 PM error [database::migrations] failed to migrate database
2023-04-16 07:16:55,045 PM error [database::migrations] Failed to migrate database... exiting...
2023-04-16 07:16:55,048 PM error [database::migrations] Error: P3009
migrate found failed migrations in the target database, new migrations will not be applied. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve
The `20210925030428_vanity_url` migration started at 2023-04-16 19:09:50.976193 UTC failed
    at Object.<anonymous> (/zipline/node_modules/@prisma/migrate/dist/MigrateEngine.js:304:24)
    at MigrateEngine.handleResponse (/zipline/node_modules/@prisma/migrate/dist/MigrateEngine.js:157:36)
    at LineStream.<anonymous> (/zipline/node_modules/@prisma/migrate/dist/MigrateEngine.js:257:16)
    at LineStream.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at LineStream._pushBuffer (/zipline/node_modules/@prisma/migrate/dist/utils/byline.js:104:17)
    at LineStream._transform (/zipline/node_modules/@prisma/migrate/dist/utils/byline.js:98:8)
    at Transform._write (node:internal/streams/transform:175:8)
```

### Additional Info

Here is my compose file:

version: '3'
services:
  db:
    image: postgres:15
    container_name: zipline_db
    restart: unless-stopped
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=zipdb
    volumes:
      - /volume1/docker/zipline/pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  zipline:
    image: ghcr.io/diced/zipline:latest
    container_name: zipline
    ports:
      - 6500:6500
    restart: unless-stopped
    environment:
      - WEBSITE_SHOW_FILES_PER_USER=true
      - CORE_RETURN_HTTPS=false
      - CORE_SECRET=###
      - CORE_HOST=0.0.0.0
      - CORE_PORT=6500
      - CORE_DATABASE_URL=postgres://postgres:postgres@zipline_db:5432/zipdb
      - CORE_LOGGER=true
    volumes:
      - /volume1/docker/zipline/uploads:/zipline/uploads
      - /volume1/docker/zipline/public:/zipline/public
    depends_on:
      - db

volumes:
  db:
  uploads:
  public:

**Comment by danshaw** [comment]
I messed around enough with it and figured it out. False alarm.

**Comment by madindehead** [comment]
> I messed around enough with it and figured it out. False alarm.

So what was the solution?

**Comment by IceToast** [comment]
> > I messed around enough with it and figured it out. False alarm.
> 
> So what was the solution?

The solution is to activate the pgcrypto extension:
https://stackoverflow.com/questions/9025515/how-do-i-import-modules-or-install-extensions-in-postgresql-9-1
