### ISSUE TITLE
Bug: Default docker-compose doesn't work.

### ISSUE THREAD

**Issue by WinterFe** [dicedtomatoreal/typex#501]
### What happened?

Running the default configuration, with the instructions provided by the docs: https://zipline.diced.sh/docs/get-started

Immediately get the following error:
```Error: P1000: Authentication failed against database server at `postgres`, the provided database credentials for `postgres` are not valid.```

### Version

latest (ghcr.io/diced/zipline or ghcr.io/diced/zipline:latest)

### Zipline Logs

```shell
2023-12-01 04:41:28,674 PM info  [datasource] using Local(./uploads) datasource
2023-12-01 04:41:28,776 PM info  [database::migrations] establishing database connection
2023-12-01 04:41:28,777 PM info  [database::migrations] ensuring database exists, if not creating database - may error if no permissions
2023-12-01 04:41:29,020 PM error [database::migrations] Failed to migrate database... exiting...
2023-12-01 04:41:29,095 PM error [database::migrations] Error: P1000: Authentication failed against database server at `postgres`, the provided database credentials for `postgres` are not valid.
Please make sure to provide valid database credentials for the database server at `postgres`.
    at Object.ensureDatabaseExists (/zipline/node_modules/@prisma/migrate/dist/utils/ensureDatabaseExists.js:137:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at migrations (/zipline/src/server/util.ts:13:5)
    at prismaPlugin (/zipline/src/server/plugins/datasource.ts:12:3)
```

### Browser Logs
```shell
N/A
```

### Additional Info

Config is as-provided, excluding the port change & secret.
Secret is temporary keyboard-smash garbo, so who cares.

![image](https://github.com/diced/zipline/assets/42700057/c1ed9f87-3173-4aca-ac65-9d5c515fd516)

**Comment by diced** [comment]
If you have previously setup zipline with the same parent directory name, docker will create a volume called `<directory_name>_pg_data` and it will just use that old one you might have, for example: `/myzipline/...` will produce the same as `/home/user/myzipline/...`.  It might be worth checking what volumes were created in docker and if necessary deleting them (make sure you back up if you have data inside). 

The main cause of this though is postgres won't create a new user if there are users already created, so check if there are users that exist already, etc.

**Comment by diced** [comment]
Closing as stale, though I believe the problem is as stated above.
