### ISSUE TITLE
Bug: Environment variable not found: DATABASE_URL.

### ISSUE THREAD

**Issue by kanetjuh** [dicedtomatoreal/typex#502]
### What happened?

When starting I am receiving the following error
![image](https://github.com/diced/zipline/assets/50002439/31f6fa10-a4f2-4f19-a6b9-69f9afad3fcc)

```
Invalid `prisma.user.findMany()` invocation:


error: Environment variable not found: DATABASE_URL.
  -->  schema.prisma:3
   |
 2 |   provider = "postgresql"
 3 |   url      = env("DATABASE_URL")
   |

Validation Error Count: 1
    at ni.handleRequestError (\zipline\node_modules\@prisma\client\runtime\library.js:124:7090)
    at ni.handleAndLogRequestError (\zipline\node_modules\@prisma\client\runtime\library.js:124:6206)
    at ni.request (\zipline\node_modules\@prisma\client\runtime\library.js:124:5926)
    at async l (\zipline\node_modules\@prisma\client\runtime\library.js:129:10023)
    at async c (\zipline\.next\server\pages\api\auth\login.js:1:2814) {
  clientVersion: '5.6.0',
  errorCode: undefined
}

```

### Version

latest (ghcr.io/diced/zipline or ghcr.io/diced/zipline:latest)

### What browser(s) are you seeing the problem on?

Chromium-based (Chrome, Edge, Brave, Opera, mobile chrome/chromium based, etc)

### Zipline Logs

```shell
Invalid `prisma.user.findMany()` invocation:


error: Environment variable not found: DATABASE_URL.
  -->  schema.prisma:3
   |
 2 |   provider = "postgresql"
 3 |   url      = env("DATABASE_URL")
   |

Validation Error Count: 1
    at ni.handleRequestError (C:\Users\klvoe\Desktop\zipline\node_modules\@prisma\client\runtime\library.js:124:7090)
    at ni.handleAndLogRequestError (C:\Users\klvoe\Desktop\zipline\node_modules\@prisma\client\runtime\library.js:124:6206)
    at ni.request (C:\Users\klvoe\Desktop\zipline\node_modules\@prisma\client\runtime\library.js:124:5926)
    at async l (C:\Users\klvoe\Desktop\zipline\node_modules\@prisma\client\runtime\library.js:129:10023)
    at async c (C:\Users\klvoe\Desktop\zipline\.next\server\pages\api\auth\login.js:1:2814) {
  clientVersion: '5.6.0',
  errorCode: undefined
}
```

### Browser Logs

```shell
:3000/api/user:1 
        
        
        Failed to load resource: the server responded with a status of 401 (Unauthorized)
:3000/api/user:1 
        
        
        Failed to load resource: the server responded with a status of 401 (Unauthorized)
:3000/api/auth/login:1 
        
        
        Failed to load resource: the server responded with a status of 500 (Internal Server Error)
login:1  Uncaught (in promise) SyntaxError: Unexpected token 'I', "Internal S"... is not valid JSON
```

**Comment by diced** [comment]
Not able to reproduce this, make sure if this isn't running on docker to build with environment variables present, or you may be able to bypass this by having the `ZIPLINE_DOCKER_BUILD=true` environment variable present.

**Comment by diced** [comment]
Closing as stale.
