### ISSUE TITLE
Bug: Opening a folder in new tab throws 500

### ISSUE THREAD

**Issue by XeroxDev** [dicedtomatoreal/typex#505]
### What happened?

If I press "Open folder in new tab" eg. `https://domain.tld/folder/3` it throws an 500 internal server error. The only "interesting" things I could see were the logs (see below) about conversion error.

### Version

latest (ghcr.io/diced/zipline or ghcr.io/diced/zipline:latest)

### What browser(s) are you seeing the problem on?

Firefox, Chromium-based (Chrome, Edge, Brave, Opera, mobile chrome/chromium based, etc)

### Zipline Logs

```shell
zipline-zipline-1   | TypeError: Cannot convert a BigInt value to a number
zipline-zipline-1   |     at isNaN (<anonymous>)
zipline-zipline-1   |     at t (/zipline/.next/server/chunks/48139.js:1:7486)
zipline-zipline-1   |     at P (/zipline/.next/server/chunks/20936.js:1:2686)
zipline-zipline-1   |     at Wc (/zipline/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
zipline-zipline-1   |     at Zc (/zipline/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
zipline-zipline-1   |     at Z (/zipline/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
zipline-zipline-1   |     at $c (/zipline/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
zipline-zipline-1   |     at bd (/zipline/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
zipline-zipline-1   |     at Z (/zipline/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
zipline-zipline-1   |     at Zc (/zipline/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:479)
zipline-zipline-1   |  ⨯ TypeError: Cannot convert a BigInt value to a number
zipline-zipline-1   |     at isNaN (<anonymous>)
zipline-zipline-1   |     at t (/zipline/.next/server/chunks/48139.js:1:7486)
zipline-zipline-1   |     at P (/zipline/.next/server/chunks/20936.js:1:2686)
zipline-zipline-1   |     at Wc (/zipline/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
zipline-zipline-1   |     at Zc (/zipline/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
zipline-zipline-1   |     at Z (/zipline/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
zipline-zipline-1   |     at $c (/zipline/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
zipline-zipline-1   |     at bd (/zipline/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
zipline-zipline-1   |     at Z (/zipline/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
zipline-zipline-1   |     at Zc (/zipline/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:479)
```

### Additional Info

I don't think this is high priority (at least for me), but I wanted to report it.

I'm using the docker image and I just updated to the latest version (3.7.7)

Also looked through open and closed issues but didn't found anything related.

**Comment by diced** [comment]
fixed https://github.com/diced/zipline/commit/1d0bb2fa4fefc703233ebd79a4668bb8a57a900e
