### ISSUE TITLE
Bug: Failed to migrate database

### ISSUE THREAD

**Issue by JustJoostNL** [dicedtomatoreal/typex#615]
### What happened?

Zipline doesn't load anymore, due to a DB migration error.

### Version

latest (ghcr.io/diced/zipline or ghcr.io/diced/zipline:latest)

### Zipline Logs

```shell
2024-10-01 08:10:17,959 PM info  [datasource] using Local(./uploads) datasource

2024-10-01T20:10:18.020509016Z 2024-10-01 08:10:18,019 PM info  [database::migrations] establishing database connection

2024-10-01T20:10:18.021695454Z 2024-10-01 08:10:18,021 PM info  [database::migrations] ensuring database exists, if not creating database - may error if no permissions

2024-10-01T20:10:18.282627278Z 2024-10-01 08:10:18,281 PM error [database::migrations] failed to migrate database

2024-10-01T20:10:18.282664678Z 2024-10-01 08:10:18,282 PM error [database::migrations] Failed to migrate database... exiting...

2024-10-01T20:10:18.284635275Z 2024-10-01 08:10:18,283 PM error [database::migrations] Error: P3009

2024-10-01T20:10:18.284660235Z 

2024-10-01T20:10:18.284663915Z migrate found failed migrations in the target database, new migrations will not be applied. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve

2024-10-01T20:10:18.284667155Z The `20231109082848_fix_large_uploads` migration started at 2023-11-21 06:44:56.784165 UTC failed

2024-10-01T20:10:18.284670115Z 

2024-10-01T20:10:18.284672435Z 

2024-10-01T20:10:18.284674915Z     at Object.<anonymous> (/zipline/node_modules/@prisma/migrate/dist/SchemaEngine.js:415:24)

2024-10-01T20:10:18.284677755Z     at SchemaEngine.handleResponse (/zipline/node_modules/@prisma/migrate/dist/SchemaEngine.js:256:36)

2024-10-01T20:10:18.284680475Z     at LineStream.<anonymous> (/zipline/node_modules/@prisma/migrate/dist/SchemaEngine.js:363:16)

2024-10-01T20:10:18.284683315Z     at LineStream.emit (node:events:513:28)

2024-10-01T20:10:18.284686355Z     at addChunk (node:internal/streams/readable:324:12)

2024-10-01T20:10:18.284688955Z     at readableAddChunk (node:internal/streams/readable:297:9)

2024-10-01T20:10:18.284691555Z     at Readable.push (node:internal/streams/readable:234:10)

2024-10-01T20:10:18.284694115Z     at LineStream._pushBuffer (/zipline/node_modules/@prisma/migrate/dist/utils/byline.js:103:17)

2024-10-01T20:10:18.284696875Z     at LineStream._transform (/zipline/node_modules/@prisma/migrate/dist/utils/byline.js:97:8)

2024-10-01T20:10:18.284699515Z     at Transform._write (node:internal/streams/transform:175:8)
```

**Comment by JustJoostNL** [comment]
Anyone any idea? Can't seem to fix it.

**Comment by JustJoostNL** [comment]
Fixed this by manually editing the DB. But I do think someone has to look at this still, since more people could have this issue.
