### ISSUE TITLE
Bug: S3 Datasource Connection to Backblaze

### ISSUE THREAD

**Issue by abramter** [dicedtomatoreal/typex#642]
### What happened?

Added a new bucket to backblaze and setup the datasource for S3 but keep getting the same error `Invalid bucket name:` no matter what i put in the env config

Here is my docker-compose and error log

~~~
      - DATASOURCE_TYPE=s3
      - DATASOURCE_S3_ACCESS_KEY_ID={id}
      - DATASOURCE_S3_SECRET_ACCESS_KEY={ID}
      - DATASOURCE_S3_ENDPOINT=s3.us-west-000.backblazeb2.com
      - DATASOURCE_S3_BUCKET='Tnet-Zipline'
      - DATASOURCE_S3_USE_SSL=true
      - DATASOURCE_S3_FORCE_S3_PATH=false
      - DATASOURCE_S3_REGION=us-east-1
~~~
~~~
InvalidBucketNameError: Invalid bucket name: 'Tnet-Zipline'
    at Client.removeObject (/zipline/node_modules/minio/dist/main/internal/client.ts:842:13)
    at Client.removeObject (/zipline/node_modules/minio/dist/main/internal/callbackify.js:16:15)
    at S3.delete (/zipline/src/lib/datasources/S3.ts:42:15)
    at l (/zipline/.next/server/pages/api/user/files.js:1:7751)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
~~~

### Version

latest (ghcr.io/diced/zipline or ghcr.io/diced/zipline:latest)

### What browser(s) are you seeing the problem on?

Chromium-based (Chrome, Edge, Brave, Opera, mobile chrome/chromium based, etc)

### Zipline Logs

```shell
2024-12-25 12:19:08,722 AM info  [datasource] using S3('Tnet-Zipline') datasource
2024-12-25 12:19:08,915 AM info  [database::migrations] establishing database connection
2024-12-25 12:19:08,917 AM info  [database::migrations] ensuring database exists, if not creating database - may error if no permissions
2024-12-25 12:19:09,578 AM info  [database::migrations] exiting migrations engine - database is up to date
2024-12-25 12:19:18,118 AM info  [server] listening on 0.0.0.0:3000
2024-12-25 12:19:18,118 AM info  [server] started production zipline@3.7.10 server
2024-12-25 12:19:21,554 AM info  [server::response] GET /dashboard -> 200
2024-12-25 12:19:22,208 AM info  [server::response] GET /api/user -> 200
2024-12-25 12:19:22,693 AM info  [server::response] GET /api/user/recent?filter=media -> 200
2024-12-25 12:19:22,725 AM info  [server::response] GET /api/user/paged?page=1&filter=none&favorite=&sortBy=&order= -> 200
2024-12-25 12:19:22,847 AM info  [server::response] GET /api/user/paged?count=true -> 200
2024-12-25 12:19:23,117 AM info  [server::response] GET /api/user/files?count=true -> 200
2024-12-25 12:19:23,123 AM info  [server::response] GET /api/stats?amount=2 -> 200
2024-12-25 12:19:23,529 AM info  [server::response] GET /api/version -> 200
2024-12-25 12:19:24,507 AM info  [server::response] GET /api/user/paged?page=1&filter=media&favorite=&sortBy=&order= -> 200
2024-12-25 12:19:24,512 AM info  [server::response] GET /api/user/paged?count=true&filter=media&favorite=true -> 200
2024-12-25 12:19:24,522 AM info  [server::response] GET /api/user/paged?page=1&filter=media&favorite=true&sortBy=&order= -> 200
2024-12-25 12:19:24,526 AM info  [server::response] GET /api/user/pending -> 200
2024-12-25 12:19:24,540 AM info  [server::response] GET /api/user/paged?count=true&filter=media&favorite=true -> 200
2024-12-25 12:19:24,588 AM info  [server::response] GET /api/user/paged?count=true&filter=media -> 200
2024-12-25 12:19:24,591 AM info  [server::response] GET /api/user/paged?count=true&filter=media&favorite=true -> 200
2024-12-25 12:19:28,152 AM info  [server::response] GET /api/version -> 200
InvalidBucketNameError: Invalid bucket name: 'Tnet-Zipline'
    at putObject (/zipline/node_modules/minio/dist/main/minio.js:578:13)
    at <anonymous> (/zipline/node_modules/minio/dist/main/promisify.js:28:10)
    at new Promise (<anonymous>)
    at Client.<anonymous> (/zipline/node_modules/minio/dist/main/promisify.js:17:12)
    at S3.save (/zipline/src/lib/datasources/S3.ts:32:23)
    at S (/zipline/.next/server/pages/api/upload.js:3:15031)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by adrianthehusky** [comment]
I ran into the same issue before over in #573. Even though Backblaze lets you use uppercase letters, minio doesn't accept them as valid in a bucket name. Try switching your bucket name to all lowercase.

**Comment by abramter** [comment]
That did it, working perfectly now. Thanks a lot for the help, maybe this fix should be added to the docs since so many people use backblaze.
