### ISSUE TITLE
Database ERROR in 3.2.0

### ISSUE THREAD

**Issue by mzch** [dicedtomatoreal/typex#91]
After upgrading to 3.2.0, the database error occurred.

```
Aug 27 03:00:14 ls node[422]: info: 127.0.0.1 "GET /sync?sync_id=18&type=poll" 200 27
Aug 27 03:00:16 ls start.sh[804153]: 2021-08-27 03:00:16,783 AM INFO  [url] 200: /api/auth/login
Aug 27 03:00:17 ls start.sh[804153]: PrismaClientKnownRequestError3 [PrismaClientKnownRequestError]:
Aug 27 03:00:17 ls start.sh[804153]: Invalid `prisma.user.findMany()` invocation:
Aug 27 03:00:17 ls start.sh[804153]:   The column `User.systemTheme` does not exist in the current database.
Aug 27 03:00:17 ls start.sh[804153]:     at cb (/srv/zipline/zipline/node_modules/@prisma/client/runtime/index.js:36063:17)
Aug 27 03:00:17 ls start.sh[804153]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Aug 27 03:00:17 ls start.sh[804153]:     at async handler (/srv/zipline/zipline/.next/server/pages/api/auth/login.js:76:17)
Aug 27 03:00:17 ls start.sh[804153]:     at async Object.apiResolver (/srv/zipline/zipline/node_modules/next/dist/server/api-utils.js:101:9)
Aug 27 03:00:17 ls start.sh[804153]:     at async Server.handleApiRequest (/srv/zipline/zipline/node_modules/next/dist/server/next-server.js:760:9)
Aug 27 03:00:17 ls start.sh[804153]:     at async Object.fn (/srv/zipline/zipline/node_modules/next/dist/server/next-server.js:651:37)
Aug 27 03:00:17 ls start.sh[804153]:     at async Router.execute (/srv/zipline/zipline/node_modules/next/dist/server/router.js:205:32)
Aug 27 03:00:17 ls start.sh[804153]:     at async Server.run (/srv/zipline/zipline/node_modules/next/dist/server/next-server.js:825:29)
Aug 27 03:00:17 ls start.sh[804153]:     at async Server.handleRequest (/srv/zipline/zipline/node_modules/next/dist/server/next-server.js:292:20) {
Aug 27 03:00:17 ls start.sh[804153]:   code: 'P2022',
Aug 27 03:00:17 ls start.sh[804153]:   clientVersion: '2.30.0',
Aug 27 03:00:17 ls start.sh[804153]:   meta: { column: 'User.systemTheme' }
Aug 27 03:00:17 ls start.sh[804153]: }
```

**Comment by mzch** [comment]
I executed `ALTER TABLE "User" ADD COLUMN     "systemTheme" TEXT NOT NULL DEFAULT E'dark_blue';` manually and tried.
Then I can login successfully but immediately zipline shows login screen again.

```
Aug 27 03:35:03 ls start.sh[805934]: 2021-08-27 03:35:03,744 AM INFO  [url] 200: /api/auth/login
Aug 27 03:35:03 ls start.sh[805934]: 2021-08-27 03:35:03,764 AM INFO  [user] User mzch (1) logged in
Aug 27 03:35:03 ls start.sh[805934]: 2021-08-27 03:35:03,991 AM INFO  [url] 200: /api/user
Aug 27 03:35:04 ls start.sh[805934]: 2021-08-27 03:35:04,158 AM INFO  [url] 200: /api/user
Aug 27 03:35:20 ls start.sh[805934]: 2021-08-27 03:35:20,390 AM INFO  [url] 200: /auth/login
Aug 27 03:35:20 ls start.sh[805934]: 2021-08-27 03:35:20,856 AM INFO  [url] 200: /api/user
Aug 27 03:35:21 ls start.sh[805934]: 2021-08-27 03:35:21,025 AM INFO  [url] 200: /favicon.ico
Aug 27 03:35:38 ls start.sh[805934]: 2021-08-27 03:35:38,839 AM INFO  [url] 200: /api/auth/login
Aug 27 03:35:38 ls start.sh[805934]: 2021-08-27 03:35:38,850 AM INFO  [user] User mzch (1) logged in
Aug 27 03:35:39 ls start.sh[805934]: 2021-08-27 03:35:39,089 AM INFO  [url] 200: /api/user
Aug 27 03:35:39 ls start.sh[805934]: 2021-08-27 03:35:39,250 AM INFO  [url] 200: /api/user
```

**Comment by diced** [comment]
You might be able to fix this by running `UPDATE "_prisma_migrations" SET migration_name = '20210825043706_init'`, but im not sure why this is happening.

**Comment by mzch** [comment]
Unfortunatlly,it doesn't fix this issue.

I reinstall Zipline refreshlly. Tables are created but default user isn't created. In  3.1.0 admin user was created.

**Comment by diced** [comment]
The default user is created upon the first login, so when you login for the first time with `administrator`:`password` it'll create the account and login

**Comment by mzch** [comment]
I tried to login with `administrator:password` but an error occrurred.
```
ug 27 14:54:57 lo yarn[155219]: Invalid `prisma.user.findMany()` invocation:
Aug 27 14:54:57 lo yarn[155219]:   The table `public.User` does not exist in the current database.
Aug 27 14:54:57 lo yarn[155219]:     at cb (/srv/zipline/zipline/node_modules/@prisma/client/runtime/index.js:36063:17)
Aug 27 14:54:57 lo yarn[155219]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Aug 27 14:54:57 lo yarn[155219]:     at async handler (/srv/zipline/zipline/.next/server/pages/api/auth/login.js:76:17)
Aug 27 14:54:57 lo yarn[155219]:     at async Object.apiResolver (/srv/zipline/zipline/node_modules/next/dist/server/api-utils.js:101:9)
Aug 27 14:54:57 lo yarn[155219]:     at async Server.handleApiRequest (/srv/zipline/zipline/node_modules/next/dist/server/next-server.js:760:9)
Aug 27 14:54:57 lo yarn[155219]:     at async Object.fn (/srv/zipline/zipline/node_modules/next/dist/server/next-server.js:651:37)
Aug 27 14:54:57 lo yarn[155219]:     at async Router.execute (/srv/zipline/zipline/node_modules/next/dist/server/router.js:205:32)
Aug 27 14:54:57 lo yarn[155219]:     at async Server.run (/srv/zipline/zipline/node_modules/next/dist/server/next-server.js:825:29)
Aug 27 14:54:57 lo yarn[155219]:     at async Server.handleRequest (/srv/zipline/zipline/node_modules/next/dist/server/next-server.js:292:20) {
Aug 27 14:54:57 lo yarn[155219]:   code: 'P2021',
Aug 27 14:54:57 lo yarn[155219]:   clientVersion: '2.30.0',
Aug 27 14:54:57 lo yarn[155219]:   meta: { table: 'public.User' }
Aug 27 14:54:57 lo yarn[155219]: }
```

**Comment by diced** [comment]
honestly don't know what's happening, since I've never come across this with testing & not able to reproduce it... Only thing I can suggest now is to reset the database

**Comment by mzch** [comment]
Oh, I missed a notice in boot log. I ran `yarn prisma migrate deploy` manually, then restarted Zipline. I can login with `administrator` successfully. Thanks!

p.s.
Please add this step in your document. This step needs `DATABASE_URL` environment variable.
